### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by xiaoLiu0531** [ChristopheZhao/ChaGPT-API-Call#9]
Hello，ChatGPT on the web page can use the conversation normally, but the error "You exceeded your current quota, please check your plan and billing details." is displayed through the API interface.

**Comment by ChristopheZhao** [comment]
As the error info above,It tips that  your openai account dont support to call the api now,maybe you need  to charge after check your account.

**Comment by xiaoLiu0531** [comment]
Ok, I'm going to check my account, thank you for your answer.
